version: "3.7"
services:
  nginx:
    image: nginx:latest
    networks:
      - network
    volumes:
      - /home/django-course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
  django_container_gunicorn:
    image: django_v6
    networks:
      - network
    volumes:
      - static-volume:/home/PZONE-Django-Test/P_ZONE_NOTICE/staticfiles/
      - media-volume:/home/P_ZONE_Cloud/media/
  test2-model-svc:
    image: model_v6
    networks:
      - network


networks:
  network:

volumes:
  static-volume:
  media-volume:

